   name: Dockerfile Lint

   on:
     push:
       branches:
         - master
       paths:
         - "**/Dockerfile"
     pull_request:
       paths:
         - "**/Dockerfile"

   jobs:
     hadolint:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v3

         - name: Run Hadolint
           uses: hadolint/hadolint-action@v2.7.0
           with:
             dockerfile: ./Dockerfile
