# .github/workflows/trivy.yml
   name: Trivy Vulnerability Scan

   on:
     push:
       branches:
         - master

   jobs:
     trivy:
       runs-on: ubuntu-latest
       env:
         TRIVY_SEVERITY: CRITICAL
         DOCKER_IMAGE: myapp:${{ github.sha }}
       steps:
         - uses: actions/checkout@v3

         - name: Build Docker image
           run: docker build -t $DOCKER_IMAGE .

         - name: Run Trivy vulnerability scanner
           uses: aquasecurity/trivy-action@master
           with:
             image-ref: 'eitanburg/javapp:t1'
             format: 'table'
             exit-code: '1'
             ignore-unfixed: true
             vuln-type: 'os,library'
             severity: 'CRITICAL,HIGH'
